/*  Technoologies Speed     */UPDATE Technologies SET Cost = Cost*1.2 WHERE EraType ='ERA_ANCIENT';
/*  Technoologies Speed     */UPDATE Technologies SET Cost = Cost*1.2 WHERE EraType ='ERA_CLASSICAL';
/*  Technoologies Speed     */UPDATE Technologies SET Cost = Cost*1.3 WHERE EraType ='ERA_MEDIEVAL';
/*  Technoologies Speed     */UPDATE Technologies SET Cost = Cost*1.5 WHERE EraType ='ERA_RENAISSANCE';
/*  Technoologies Speed     */UPDATE Technologies SET Cost = Cost*1.6 WHERE EraType ='ERA_INDUSTRIAL';
/*  Technoologies Speed     */UPDATE Technologies SET Cost = Cost*1.7 WHERE EraType ='ERA_MODERN';
/*  Technoologies Speed     */UPDATE Technologies SET Cost = Cost*1.7 WHERE EraType ='ERA_ATOMIC';
/*  Technoologies Speed     */UPDATE Technologies SET Cost = Cost*1.8 WHERE EraType ='ERA_INFORMATION';
/*  Civics Speed            */UPDATE Civics SET Cost = Cost*1.2 WHERE EraType ='ERA_ANCIENT';
/*  Civics Speed            */UPDATE Civics SET Cost = Cost*1.2 WHERE EraType ='ERA_CLASSICAL';
/*  Civics Speed            */UPDATE Civics SET Cost = Cost*1.3 WHERE EraType ='ERA_MEDIEVAL';
/*  Civics Speed            */UPDATE Civics SET Cost = Cost*1.5 WHERE EraType ='ERA_RENAISSANCE';
/*  Civics Speed            */UPDATE Civics SET Cost = Cost*1.6 WHERE EraType ='ERA_INDUSTRIAL';
/*  Civics Speed            */UPDATE Civics SET Cost = Cost*1.7 WHERE EraType ='ERA_MODERN';
/*  Civics Speed            */UPDATE Civics SET Cost = Cost*1.7 WHERE EraType ='ERA_ATOMIC';
/*  Civics Speed            */UPDATE Civics SET Cost = Cost*1.8 WHERE EraType ='ERA_INFORMATION';
/*  GreatPerson Speed       */UPDATE Eras SET GreatPersonBaseCost = GreatPersonBaseCost*1.2 WHERE EraType = 'ERA_ANCIENT';
/*  GreatPerson Speed       */UPDATE Eras SET GreatPersonBaseCost = GreatPersonBaseCost*1.2 WHERE EraType = 'ERA_CLASSICAL';
/*  GreatPerson Speed       */UPDATE Eras SET GreatPersonBaseCost = GreatPersonBaseCost*1.3 WHERE EraType = 'ERA_MEDIEVAL';
/*  GreatPerson Speed       */UPDATE Eras SET GreatPersonBaseCost = GreatPersonBaseCost*1.5 WHERE EraType = 'ERA_RENAISSANCE';
/*  GreatPerson Speed       */UPDATE Eras SET GreatPersonBaseCost = GreatPersonBaseCost*1.6 WHERE EraType = 'ERA_INDUSTRIAL';
/*  GreatPerson Speed       */UPDATE Eras SET GreatPersonBaseCost = GreatPersonBaseCost*1.7 WHERE EraType = 'ERA_MODERN';
/*  GreatPerson Speed       */UPDATE Eras SET GreatPersonBaseCost = GreatPersonBaseCost*1.7 WHERE EraType = 'ERA_ATOMIC';
/*  GreatPerson Speed       */UPDATE Eras SET GreatPersonBaseCost = GreatPersonBaseCost*1.8 WHERE EraType = 'ERA_INFORMATION';