/* no EPIC      */DELETE FROM GameSpeeds WHERE Name = 'LOC_GAMESPEED_EPIC_NAME';
/* no STANDARD  */DELETE FROM GameSpeeds WHERE Name = 'LOC_GAMESPEED_STANDARD_NAME';
/* no QUICK     */DELETE FROM GameSpeeds WHERE Name = 'LOC_GAMESPEED_QUICK_NAME';
/* no ONLINE    */DELETE FROM GameSpeeds WHERE Name = 'LOC_GAMESPEED_ONLINE_NAME';