/*  Settler                 */UPDATE Units SET Cost='80', Maintenance='1' WHERE Name='LOC_UNIT_SETTLER_NAME'; 
/*  Builder                 */UPDATE Units SET Cost='40', Maintenance='1' WHERE Name='LOC_UNIT_BUILDER_NAME'; 
/*  Trader                  */UPDATE Units SET Cost='25', Maintenance='0' WHERE Name='LOC_UNIT_TRADER_NAME'; 
/*  Missionary              */UPDATE Units SET Cost='50', Maintenance='1' WHERE Name='LOC_UNIT_MISSIONARY_NAME'; 
/*  Apostle                 */UPDATE Units SET Cost='140', Maintenance='1' WHERE Name='LOC_UNIT_APOSTLE_NAME'; 
/*  Inquisitor              */UPDATE Units SET Cost='50', Maintenance='1' WHERE Name='LOC_UNIT_INQUISITOR_NAME'; 
/*  Archaeologist           */UPDATE Units SET Cost='275', Maintenance='2' WHERE Name='LOC_UNIT_ARCHAEOLOGIST_NAME'; 
/*  Spy                     */UPDATE Units SET Cost='200', Maintenance='5' WHERE Name='LOC_UNIT_SPY_NAME'; 
/*  Naturalist              */UPDATE Units SET Cost='650', Maintenance='4' WHERE Name='LOC_UNIT_NATURALIST_NAME'; 
/*  Scout                   */UPDATE Units SET Cost='12', Maintenance='0' WHERE Name='LOC_UNIT_SCOUT_NAME'; 
/*  Warrior                 */UPDATE Units SET Cost='16', Maintenance='1' WHERE Name='LOC_UNIT_WARRIOR_NAME'; 
/*  Slinger                 */UPDATE Units SET Cost='12', Maintenance='1' WHERE Name='LOC_UNIT_SLINGER_NAME'; 
/*  Barbarian Horseman      */UPDATE Units SET Cost='25', Maintenance='1' WHERE Name='LOC_UNIT_BARBARIAN_HORSEMAN_NAME';
/*  Barbarian Horse Archer  */UPDATE Units SET Cost='25', Maintenance='1' WHERE Name='LOC_UNIT_BARBARIAN_HORSE_ARCHER_NAME';
/*  War Cart                */UPDATE Units SET Cost='30', Maintenance='1' WHERE Name='LOC_UNIT_SUMERIAN_WAR_CART_NAME'; 
/*  Barbarian Galley        */UPDATE Units SET Cost='40', Maintenance='1' WHERE Name='LOC_UNIT_BARBARIAN_GALLEY_NAME';
/*  Galley                  */UPDATE Units SET Cost='40', Maintenance='2' WHERE Name='LOC_UNIT_GALLEY_NAME'; 
/*  Longship                */UPDATE Units SET Cost='40', Maintenance='2' WHERE Name='LOC_UNIT_NORWEGIAN_LONGSHIP_NAME'; 
/*  Archer                  */UPDATE Units SET Cost='20', Maintenance='2' WHERE Name='LOC_UNIT_ARCHER_NAME'; 
/*  Spearman                */UPDATE Units SET Cost='25', Maintenance='2' WHERE Name='LOC_UNIT_SPEARMAN_NAME'; 
/*  Heavy Chariot           */UPDATE Units SET Cost='35', Maintenance='2' WHERE Name='LOC_UNIT_HEAVY_CHARIOT_NAME'; 
/*  Battering Ram           */UPDATE Units SET Cost='35', Maintenance='2' WHERE Name='LOC_UNIT_BATTERING_RAM_NAME'; 
/*  Hoplite                 */UPDATE Units SET Cost='25', Maintenance='2' WHERE Name='LOC_UNIT_GREEK_HOPLITE_NAME'; 
/*  Swordsman               */UPDATE Units SET Cost='35', Maintenance='3' WHERE Name='LOC_UNIT_SWORDSMAN_NAME'; 
/*  Horsman                 */UPDATE Units SET Cost='40', Maintenance='3' WHERE Name='LOC_UNIT_HORSEMAN_NAME'; 
/*  Horse Archer            */UPDATE Units SET Cost='50', Maintenance='3' WHERE Name='LOC_UNIT_SCYTHIAN_HORSE_ARCHER_NAME'; 
/*  Legion                  */UPDATE Units SET Cost='40', Maintenance='3' WHERE Name='LOC_UNIT_ROMAN_LEGION_NAME'; 
/*  Shield Bearer           */UPDATE Units SET Cost='40', Maintenance='3' WHERE Name='LOC_UNIT_KONGO_SHIELD_BEARER_NAME'; 
/*  Catapult                */UPDATE Units SET Cost='50', Maintenance='3' WHERE Name='LOC_UNIT_CATAPULT_NAME'; 
/*  Siege Tower             */UPDATE Units SET Cost='50', Maintenance='3' WHERE Name='LOC_UNIT_SIEGE_TOWER_NAME'; 
/*  Quadrireme              */UPDATE Units SET Cost='75', Maintenance='3' WHERE Name='LOC_UNIT_QUADRIREME_NAME'; 
/*  Chariot Archer          */UPDATE Units SET Cost='75', Maintenance='3' WHERE Name='LOC_UNIT_EGYPTIAN_CHARIOT_ARCHER_NAME'; 
/*  Samurai                 */UPDATE Units SET Cost='60', Maintenance='4' WHERE Name='LOC_UNIT_JAPANESE_SAMURAI_NAME'; 
/*  Berserker               */UPDATE Units SET Cost='60', Maintenance='4' WHERE Name='LOC_UNIT_NORWEGIAN_BERSERKER_NAME'; 
/*  Knight                  */UPDATE Units SET Cost='85', Maintenance='4' WHERE Name='LOC_UNIT_KNIGHT_NAME'; 
/*  Varu                    */UPDATE Units SET Cost='70', Maintenance='4' WHERE Name='LOC_UNIT_INDIAN_VARU_NAME'; 
/*  Mamluk                  */UPDATE Units SET Cost='85', Maintenance='4' WHERE Name='LOC_UNIT_ARABIAN_MAMLUK_NAME'; 
/*  Crossbowman             */UPDATE Units SET Cost='60', Maintenance='4' WHERE Name='LOC_UNIT_CROSSBOWMAN_NAME'; 
/*  Crouching Tiger         */UPDATE Units SET Cost='55', Maintenance='4' WHERE Name='LOC_UNIT_CHINESE_CROUCHING_TIGER_NAME'; 
/*  Military Engineer       */UPDATE Units SET Cost='60', Maintenance='4' WHERE Name='LOC_UNIT_MILITARY_ENGINEER_NAME'; 
/*  Pikeman                 */UPDATE Units SET Cost='65', Maintenance='4' WHERE Name='LOC_UNIT_PIKEMAN_NAME'; 
/*  Musketman               */UPDATE Units SET Cost='80', Maintenance='5' WHERE Name='LOC_UNIT_MUSKETMAN_NAME'; 
/*  Conquistador            */UPDATE Units SET Cost='125', Maintenance='5' WHERE Name='LOC_UNIT_SPANISH_CONQUISTADOR_NAME'; 
/*  Carvel                  */UPDATE Units SET Cost='140', Maintenance='5' WHERE Name='LOC_UNIT_CARAVEL_NAME'; 
/*  Bombard                 */UPDATE Units SET Cost='100', Maintenance='5' WHERE Name='LOC_UNIT_BOMBARD_NAME'; 
/*  Frigate                 */UPDATE Units SET Cost='160', Maintenance='6' WHERE Name='LOC_UNIT_FRIGATE_NAME'; 
/*  Privateer               */UPDATE Units SET Cost='160', Maintenance='5' WHERE Name='LOC_UNIT_PRIVATEER_NAME'; 
/*  Seadog                  */UPDATE Units SET Cost='160', Maintenance='5' WHERE Name='LOC_UNIT_ENGLISH_SEADOG_NAME'; 
/*  Field Cannon            */UPDATE Units SET Cost='115', Maintenance='6' WHERE Name='LOC_UNIT_FIELD_CANNON_NAME'; 
/*  Cavalry                 */UPDATE Units SET Cost='165', Maintenance='6' WHERE Name='LOC_UNIT_CAVALRY_NAME'; 
/*  Cossack                 */UPDATE Units SET Cost='170', Maintenance='6' WHERE Name='LOC_UNIT_RUSSIAN_COSSACK_NAME'; 
/*  Redcoat                 */UPDATE Units SET Cost='130', Maintenance='6' WHERE Name='LOC_UNIT_ENGLISH_REDCOAT_NAME'; 
/*  Garde Imperiale         */UPDATE Units SET Cost='130', Maintenance='6' WHERE Name='LOC_UNIT_FRENCH_GARDE_IMPERIALE_NAME'; 
/*  Medic                   */UPDATE Units SET Cost='110', Maintenance='6' WHERE Name='LOC_UNIT_MEDIC_NAME'; 
/*  Ironclad                */UPDATE Units SET Cost='220', Maintenance='6' WHERE Name='LOC_UNIT_IRONCLAD_NAME'; 
/*  Rough Rider             */UPDATE Units SET Cost='190', Maintenance='4' WHERE Name='LOC_UNIT_AMERICAN_ROUGH_RIDER_NAME'; 
/*  Ranger                  */UPDATE Units SET Cost='100', Maintenance='5' WHERE Name='LOC_UNIT_RANGER_NAME'; 
/*  Observation Balloon     */UPDATE Units SET Cost='120', Maintenance='3' WHERE Name='LOC_UNIT_OBSERVATION_BALLOON_NAME'; 
/*  Biplane                 */UPDATE Units SET Cost='240', Maintenance='7' WHERE Name='LOC_UNIT_BIPLANE_NAME'; 
/*  Infantry                */UPDATE Units SET Cost='145', Maintenance='6' WHERE Name='LOC_UNIT_INFANTRY_NAME'; 
/*  Artillery               */UPDATE Units SET Cost='180', Maintenance='7' WHERE Name='LOC_UNIT_ARTILLERY_NAME'; 
/*  Battleship              */UPDATE Units SET Cost='250', Maintenance='8' WHERE Name='LOC_UNIT_BATTLESHIP_NAME'; 
/*  Minas Geraes            */UPDATE Units SET Cost='250', Maintenance='8' WHERE Name='LOC_UNIT_BRAZILIAN_MINAS_GERAES_NAME'; 
/*  Submarine               */UPDATE Units SET Cost='280', Maintenance='7' WHERE Name='LOC_UNIT_SUBMARINE_NAME'; 
/*  UBoat                   */UPDATE Units SET Cost='260', Maintenance='7' WHERE Name='LOC_UNIT_GERMAN_UBOAT_NAME'; 
/*  AT Crew                 */UPDATE Units SET Cost='135', Maintenance='5' WHERE Name='LOC_UNIT_AT_CREW_NAME'; 
/*  Tank                    */UPDATE Units SET Cost='240', Maintenance='7' WHERE Name='LOC_UNIT_TANK_NAME'; 
/*  Fighter                 */UPDATE Units SET Cost='300', Maintenance='8' WHERE Name='LOC_UNIT_FIGHTER_NAME'; 
/*  P51                     */UPDATE Units SET Cost='300', Maintenance='8' WHERE Name='LOC_UNIT_AMERICAN_P51_NAME'; 
/*  Bomber                  */UPDATE Units SET Cost='300', Maintenance='8' WHERE Name='LOC_UNIT_BOMBER_NAME'; 
/*  Antiair Gun             */UPDATE Units SET Cost='180', Maintenance='6' WHERE Name='LOC_UNIT_ANTIAIR_GUN_NAME'; 
/*  Machine Gun             */UPDATE Units SET Cost='170', Maintenance='6' WHERE Name='LOC_UNIT_MACHINE_GUN_NAME'; 
/*  Aircraft Carrier        */UPDATE Units SET Cost='400', Maintenance='10' WHERE Name='LOC_UNIT_AIRCRAFT_CARRIER_NAME'; 
/*  Destroyer               */UPDATE Units SET Cost='350', Maintenance='8' WHERE Name='LOC_UNIT_DESTROYER_NAME'; 
/*  Helicopeter             */UPDATE Units SET Cost='350', Maintenance='8' WHERE Name='LOC_UNIT_HELICOPTER_NAME'; 
/*  Nuclear Submarine       */UPDATE Units SET Cost='400', Maintenance='9' WHERE Name='LOC_UNIT_NUCLEAR_SUBMARINE_NAME'; 
/*  Mechanized Infantry     */UPDATE Units SET Cost='280', Maintenance='8' WHERE Name='LOC_UNIT_MECHANIZED_INFANTRY_NAME'; 
/*  Rocket Artillery        */UPDATE Units SET Cost='320', Maintenance='9' WHERE Name='LOC_UNIT_ROCKET_ARTILLERY_NAME'; 
/*  Mobile SAM              */UPDATE Units SET Cost='280', Maintenance='8' WHERE Name='LOC_UNIT_MOBILE_SAM_NAME'; 
/*  Jet Fighter             */UPDATE Units SET Cost='400', Maintenance='9' WHERE Name='LOC_UNIT_JET_FIGHTER_NAME'; 
/*  Jet Bomber              */UPDATE Units SET Cost='440', Maintenance='9' WHERE Name='LOC_UNIT_JET_BOMBER_NAME'; 
/*  Missile Cruiser         */UPDATE Units SET Cost='400', Maintenance='9' WHERE Name='LOC_UNIT_MISSILE_CRUISER_NAME'; 
/*  Modern AT               */UPDATE Units SET Cost='195', Maintenance='8' WHERE Name='LOC_UNIT_MODERN_AT_NAME'; 
/*  Modern Armor            */UPDATE Units SET Cost='350', Maintenance='9' WHERE Name='LOC_UNIT_MODERN_ARMOR_NAME'; 
/*  Digger                  */UPDATE Units SET Cost='145', Maintenance='6' WHERE Name='LOC_UNIT_DIGGER_NAME'; 
/*  Eagle Warrior           */UPDATE Units SET Cost='20', Maintenance='1' WHERE Name='LOC_UNIT_AZTEC_EAGLE_WARRIOR_NAME';
/*  Hussar                  */UPDATE Units SET Cost='125', Maintenance='4' WHERE Name='LOC_UNIT_POLISH_HUSSAR_NAME';   