/*  Settler        */UPDATE Units SET Cost='80', Maintenance='1' WHERE Name='LOC_UNIT_SETTLER_NAME'; 
/*  Builder        */UPDATE Units SET Cost='40', Maintenance='1' WHERE Name='LOC_UNIT_BUILDER_NAME'; 
/*  Trader         */UPDATE Units SET Cost='25', Maintenance='0' WHERE Name='LOC_UNIT_TRADER_NAME'; 
/*  Missionary     */UPDATE Units SET Cost='50', Maintenance='1' WHERE Name='LOC_UNIT_MISSIONARY_NAME'; 
/*  Apostle        */UPDATE Units SET Cost='140', Maintenance='1' WHERE Name='LOC_UNIT_APOSTLE_NAME'; 
/*  Inquisitor     */UPDATE Units SET Cost='50', Maintenance='1' WHERE Name='LOC_UNIT_INQUISITOR_NAME'; 
/*  Archaeologist  */UPDATE Units SET Cost='275', Maintenance='2' WHERE Name='LOC_UNIT_ARCHAEOLOGIST_NAME'; 
/*  Spy            */UPDATE Units SET Cost='200', Maintenance='5' WHERE Name='LOC_UNIT_SPY_NAME'; 
/*  Naturalist     */UPDATE Units SET Cost='650', Maintenance='4' WHERE Name='LOC_UNIT_NATURALIST_NAME'; 
/*  Scout          */UPDATE Units SET Cost='15', Maintenance='0' WHERE Name='LOC_UNIT_SCOUT_NAME'; 
/*  Warrior        */UPDATE Units SET Cost='20', Maintenance='1' WHERE Name='LOC_UNIT_WARRIOR_NAME'; 
/*  Slinger        */UPDATE Units SET Cost='20', Maintenance='1' WHERE Name='LOC_UNIT_SLINGER_NAME'; 
/*  War Cart       */UPDATE Units SET Cost='27', Maintenance='1' WHERE Name='LOC_UNIT_SUMERIAN_WAR_CART_NAME'; 
/*  Galley         */UPDATE Units SET Cost='32', Maintenance='2' WHERE Name='LOC_UNIT_GALLEY_NAME'; 
/*  Archer         */UPDATE Units SET Cost='27', Maintenance='2' WHERE Name='LOC_UNIT_ARCHER_NAME'; 
/*  Spearman       */UPDATE Units SET Cost='35', Maintenance='2' WHERE Name='LOC_UNIT_SPEARMAN_NAME'; 
/*  Heavy Chariot  */UPDATE Units SET Cost='35', Maintenance='2' WHERE Name='LOC_UNIT_HEAVY_CHARIOT_NAME'; 
/*  Battering Ram  */UPDATE Units SET Cost='35', Maintenance='' WHERE Name='LOC_UNIT__NAME'; 
/*  Hoplite        */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_GREEK_HOPLITE_NAME'; 
/*  Swordsman      */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_SWORDSMAN_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_HORSEMAN_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_SCYTHIAN_HORSE_ARCHER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_ROMAN_LEGION_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_KONGO_SHIELD_BEARER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_CATAPULT_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_SIEGE_TOWER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_QUADRIREME_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_EGYPTIAN_CHARIOT_ARCHER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_JAPANESE_SAMURAI_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_NORWEGIAN_BERSERKER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_KNIGHT_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_INDIAN_VARU_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_ARABIAN_MAMLUK_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_CROSSBOWMAN_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_CHINESE_CROUCHING_TIGER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_MILITARY_ENGINEER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_PIKEMAN_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_MUSKETMAN_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_SPANISH_CONQUISTADOR_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_CARAVEL_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_BOMBARD_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_FRIGATE_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_PRIVATEER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_ENGLISH_SEADOG_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_FIELD_CANNON_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_CAVALRY_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_RUSSIAN_COSSACK_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_ENGLISH_REDCOAT_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_FRENCH_GARDE_IMPERIALE_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_MEDIC_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_IRONCLAD_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_AMERICAN_ROUGH_RIDER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_RANGER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_OBSERVATION_BALLOON_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_BIPLANE_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_INFANTRY_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_ARTILLERY_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_BATTLESHIP_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_BRAZILIAN_MINAS_GERAES_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_SUBMARINE_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_GERMAN_UBOAT_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_AT_CREW_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_TANK_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_FIGHTER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_AMERICAN_P51_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_BOMBER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_ANTIAIR_GUN_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_MACHINE_GUN_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_AIRCRAFT_CARRIER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_DESTROYER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_HELICOPTER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_NUCLEAR_SUBMARINE_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_MECHANIZED_INFANTRY_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_ROCKET_ARTILLERY_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_MOBILE_SAM_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_JET_FIGHTER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_JET_BOMBER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_MISSILE_CRUISER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_MODERN_AT_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_MODERN_ARMOR_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_DIGGER_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_AZTEC_EAGLE_WARRIOR_NAME'; 
/*                 */UPDATE Units SET Cost='', Maintenance='' WHERE Name='LOC_UNIT_POLISH_HUSSAR_NAME'; 